routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('web.home');
});*/

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index')->name('admin.dashboard'); 
    
}); 

Route::middleware('auth')->group(function () {
    Route::middleware('verified')->group(function () {
        
        Route::name('admin.')->prefix('admin')->group(function () {
            Route::get('/', 'App\Http\Controllers\Admin\DashboardController@index');
            Route::get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index')->name('dashboard');

            Route::name('profil.')->prefix('profil')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\ProfilController@index')->name('index'); 
                Route::put('/', 'App\Http\Controllers\Admin\ProfilController@update')->name('update'); 
            });
            

            Route::name('artikel.')->prefix('artikel')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\ArtikelController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\ArtikelController@dt')->name('dt');
                Route::get('/create', 'App\Http\Controllers\Admin\ArtikelController@create')->name('create'); 
                Route::get('/edit/{id}', 'App\Http\Controllers\Admin\ArtikelController@edit')->name('edit'); 
                Route::post('/store', 'App\Http\Controllers\Admin\ArtikelController@store')->name('store');
                Route::put('/update/{id}', 'App\Http\Controllers\Admin\ArtikelController@update')->name('update');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\ArtikelController@destroy')->name('delete');  
            });

            Route::name('kategori.')->prefix('kategori')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\KategoriController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\KategoriController@dt')->name('dt'); 
                Route::get('/create', 'App\Http\Controllers\Admin\KategoriController@create')->name('create'); 
                Route::post('/store', 'App\Http\Controllers\Admin\KategoriController@store')->name('store');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\KategoriController@destroy')->name('delete'); 
            });

            Route::name('pengguna.')->prefix('pengguna')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\PenggunaController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\PenggunaController@dt')->name('dt'); 
                Route::get('/create', 'App\Http\Controllers\Admin\PenggunaController@create')->name('create'); 
                Route::get('/edit/{id}', 'App\Http\Controllers\Admin\PenggunaController@edit')->name('edit'); 
                Route::post('/store', 'App\Http\Controllers\Admin\PenggunaController@store')->name('store');
                Route::put('/update/{id}', 'App\Http\Controllers\Admin\PenggunaController@update')->name('update');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\PenggunaController@destroy')->name('delete'); 
            });

        });
    }); 
}); 

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/seeallartikel', [App\Http\Controllers\HomeController::class, 'seeAllArtikel'])->name('seeall');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('kategori/{slug}', [App\Http\Controllers\KategoriController::class, 'getSlug'])->name('kategori');
Route::get('artikel/{slug}', [App\Http\Controllers\ArtikelController::class, 'seeArtikel'])->name('artikel');


// Route::resource('user', [App\Http\Controllers\PenggunaController::class, 'index']);

// login google
Route::get('login/google', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('/login/google/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGoogleCallback']);

Route::get('/instagram', function () {
    return view('web.instagramporto');
});

app/Http/Controllers/Admin/PenggunaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth; 
use Illuminate\Validation\Rules\Password;
use Illuminate\Support\Facades\Hash; 
use Illuminate\Support\Facades\Session;
use DataTables;
use Illuminate\Support\Facades\DB;

class PenggunaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.pengguna.index');
    }

    public function dt(Request $request)
    {
        $data = User::with('roles');
        return Datatables::eloquent($data)
                ->addIndexColumn()
                ->addColumn('role', function($row){
                        return $row->roles[0]->name;
                })
                ->addColumn('action', function($row){
                        $rot = $row->id;
                        $btn = "<div class=\"float-right\"><a href=\"".route('admin.pengguna.edit', ['id' => $row->id])."\" class=\"btn btn-primary btn-warning\">Edit</a> <button type=\"button\" id=\"$rot\" data-link=\"".route('admin.pengguna.delete', ['id' => $row->id])."\" onclick=\"hapus($rot)\" class=\"btn btn-danger\" data-toggle=\"modal\" data-target=\"#modal-sm\">Delete</button></div>";
                        return $btn;
                })
                ->rawColumns(['action','role'])
                ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $role = Role::all();
        return view('admin.pengguna.create')->with(compact('role'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validated = $request->validate([
            'name'                  => ['required', 'max:255'], 
            'email'                 => ['required', 'email', 'max:255', 'unique:users,email'], 
            'role'                  => 'required|exists:roles,id',
            'password'              => ['required', 'max:255', Password::min(6)->mixedCase()->numbers()]
        ]);

        DB::beginTransaction(); 

        try {
            $user = new User();

            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = Hash::make($request->password);
            $user->save();
            //cek role nama
            $role = Role::find($request->role); 
            $user->assignRole($role->name); 

            Session::flash('message', ['text'=>'User Berhasil Ditambahkan','type'=>'success']);

            DB::commit(); 

        } catch (Exception $e) {
            DB::rollback();
            Session::flash('message', ['text'=>'User Gagal Ditambahkan','type'=>'danger']);

        }

        return redirect()->route('admin.pengguna.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $dataPengguna = User::with('roles')->findOrFail($id);
        $role = Role::all();
        return view('admin.pengguna.edit')->with(compact('dataPengguna','role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        /**/
        $validated = $request->validate([
            'name'                  => ['required', 'max:255'], 
            'email'                 => ['required', 'email', 'max:255', 'unique:users,email,'.$id], 
            'role'                  => 'required|exists:roles,id',
            'password'              => ['max:255']
        ]);

        DB::beginTransaction(); 

        try {
            $user = User::find($id);

            $user->name = $request->name;
            $user->email = $request->email;
            if (strlen($request->password) != 0) {
                $user->password = Hash::make($request->password);
            }
            $user->save();
            //cek role nama
            $role = Role::find($request->role); 
            $user->assignRole($role->name); 

            Session::flash('message', ['text'=>'User Berhasil Ditambahkan','type'=>'success']);

            DB::commit(); 

        } catch (Exception $e) {
            DB::rollback();
            Session::flash('message', ['text'=>'User Gagal Ditambahkan','type'=>'danger']);

        }

        return redirect()->route('admin.pengguna.index');

        // return Auth::user()->name;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        //
        DB::beginTransaction(); 

        try {

            User::where('id',$id)->delete();

            Session::flash('message', ['text'=>'Pengguna Berhasil Dihapus','type'=>'success']);

            DB::commit(); 

        } catch (Exception $e) {
            DB::rollback();
            Session::flash('message', ['text'=>'Pengguna Gagal Dihapus','type'=>'danger']);

        }

        return redirect()->route('admin.pengguna.index');
    }
}

resources/views/admin/pengguna/create.blade.php
	@extends('admin.layout')

	@section('title', 'Create Pengguna | ' . config('app.name'))
	@section('content')
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<!-- general form elements -->
					@if ($errors->any())
					    <div class="alert alert-danger">
					        <ul>
					            @foreach ($errors->all() as $error)
					                <li>{{ $error }}</li>
					            @endforeach
					        </ul>
					    </div>
					@endif
		            <div class="card card-primary">
		              <div class="card-header">
		                <h3 class="card-title">Buat Baru Data Pengguna</h3>
		              </div>
		              <!-- /.card-header -->
		              <!-- form start -->
		              <form action="{{ route('admin.pengguna.store') }}" method="POST">
		              	@csrf
		                <div class="card-body">
							<div class="form-group">
								<label for="namaPengguna">Nama Pengguna <span class="text-danger">*</span></label>
								<input type="text" class="form-control" id="namaPengguna" name="name" placeholder="Nama Pengguna">
							</div>

							<div class="form-group">
								<label for="emailPengguna">Email Pengguna <span class="text-danger">*</span></label>
								<input type="email" class="form-control" id="emailPengguna" name="email" placeholder="Email Pengguna">
							</div>

							<div class="form-group">
								<label for="Password">Password <span class="text-danger">*</span></label>
								<input type="password" class="form-control" id="Password" name="password" placeholder="Password">
							</div>

							<div class="form-group">
								<label>Role <span class="text-danger">*</span></label>
								<select name="role" class="form-control" tabindex="3">
									<option value="">Select Role</option>
									@foreach ($role as $dataRoles)
										<option value="{{ $dataRoles->id }}">{{ strtoupper($dataRoles->name) }}</option>
									@endforeach 
								</select>
							</div>
		                </div>
		                <!-- /.card-body -->

		                <div class="card-footer">
		                  <button type="submit" class="btn btn-primary">Submit</button>
		                  <a href="{{ route('admin.pengguna.index') }}" class="btn btn-danger">Cancel</a>
		                </div>
		              </form>
		            </div>
		            <!-- /.card -->
				</div>
			</div>
		</div>
	</section>

	@endsection

resources/views/admin/pengguna/edit.blade.php
	@extends('admin.layout')

	@section('title', 'Create Pengguna | ' . config('app.name'))
	@section('content')
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<!-- general form elements -->
					@if ($errors->any())
					    <div class="alert alert-danger">
					        <ul>
					            @foreach ($errors->all() as $error)
					                <li>{{ $error }}</li>
					            @endforeach
					        </ul>
					    </div>
					@endif
		            <div class="card card-primary">
		              <div class="card-header">
		                <h3 class="card-title">Buat Baru Data Pengguna</h3>
		              </div>
		              <!-- /.card-header -->
		              <!-- form start -->
		              <form action="{{ route('admin.pengguna.update', ["id" => $dataPengguna->id]) }}" method="POST">
		              	@csrf
		              	@method('PUT')
		                <div class="card-body">
							<div class="form-group">
								<label for="namaPengguna">Nama Pengguna <span class="text-danger">*</span></label>
								<input type="text" class="form-control" id="namaPengguna" name="name" placeholder="Nama Pengguna" value="{{$dataPengguna->name}}">
							</div>

							<div class="form-group">
								<label for="emailPengguna">Email Pengguna <span class="text-danger">*</span></label>
								<input type="email" class="form-control" id="emailPengguna" name="email" placeholder="Email Pengguna" value="{{$dataPengguna->email}}">
							</div>

							<div class="form-group">
								<label for="Password">Password </label>
								<input type="password" class="form-control" id="Password" name="password" placeholder="Password">
								<small class="text-muted">Kosongkan Jika Tidak Ingin Merubah Password</small>
							</div>

							<div class="form-group">
								<label>Role <span class="text-danger">*</span></label>
								<select name="role" class="form-control" tabindex="3">
									<option value="">Select Role</option>
									@foreach ($role as $dataRoles)
										<option value="{{ $dataRoles->id }}" @if($dataPengguna->roles[0]->id == $dataRoles->id) selected @else @endif>{{ strtoupper($dataRoles->name) }}</option>
									@endforeach 
								</select>
							</div>
		                </div>
		                <!-- /.card-body -->

		                <div class="card-footer">
		                  <button type="submit" class="btn btn-primary">Submit</button>
		                  <a href="{{ route('admin.pengguna.index') }}" class="btn btn-danger">Cancel</a>
		                </div>
		              </form>
		            </div>
		            <!-- /.card -->
				</div>
			</div>
		</div>
	</section>

	@endsection

resources/views/admin/pengguna/index.blade.php
	@extends('admin.layout')

	@section('title', 'Pengguna | ' . config('app.name'))

	@push('dt-style')
		<link rel="stylesheet" href="{{ asset('admin') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
		<link rel="stylesheet" href="{{ asset('admin') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
		<link rel="stylesheet" href="{{ asset('admin') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
	@endpush

	@section('content')
	<section class="content">
    <div class="container-fluid">
    	<div class="row">
      	<div class="col-md-12">
      		@if(Session::has('message'))
					    <div class="alert alert-{{session('message')['type']}}">
					        {{session('message')['text']}}
					    </div>
					@endif
      		<div class="card">
      			<div class="card-body">
      				<div class="row">
      					<div class="col-md-6">
        					<h3>Pengguna</h3>
        				</div>
        				<div class="col-md-6">
        					<a href="{{ route('admin.pengguna.create') }}" class="btn btn-success float-right">Buat Baru</a>
        				</div>
      				</div>
      			</div>
      		</div>
      	</div>
      </div>
      <div class="row">
        <div class="col-12">

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="tabel-pengguna" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nama</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <div class="modal fade" id="modal-sm">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Konfirmasi Hapus</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Konfirmasi Untuk Menghapus</p>
          </div>
          <div class="modal-footer justify-content-between">
          	<form action="" method="POST" id="form-modal-hapus-konfirmasi">
          		@csrf
          		@method('delete')
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-danger">Delete</button>
          	</form>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
   </section>
	@endsection

	@push('dt-skrip')
		<!-- DataTables  & Plugins -->
		<script src="{{ asset('admin') }}/plugins/datatables/jquery.dataTables.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/jszip/jszip.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/pdfmake/pdfmake.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/pdfmake/vfs_fonts.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
		<script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
		<!-- SweetAlert2 -->
		<script src="{{ asset('admin') }}/plugins/sweetalert2/sweetalert2.min.js"></script>
		<!-- Toastr -->
		<script src="{{ asset('admin') }}/plugins/toastr/toastr.min.js"></script>
    <script type="text/javascript">

  	$("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
    });

    function hapus(a){
    	var url = $("#"+a).data('link');
    	$("#form-modal-hapus-konfirmasi").attr('action', url);
		}

		$(function () {

			var table = $('#tabel-pengguna').DataTable({
				processing: true,
				serverSide: true,
				"paging": true,
				"lengthChange": true,
				"searching": true,
				"ordering": true,
				"info": true,
				"autoWidth": true,
				"responsive": true,
				ajax: "{{ route('admin.pengguna.dt') }}",
				columns: [
					// {data: 'id', name: 'id'},
					{data: 'name', name: 'name'},
					{data: 'email', name: 'email'},
					{data: 'role', name: 'role'},
					{data: 'action', name: 'action', orderable: false, searchable: false},
				]
			});



		});
    </script>
	@endpush