routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('web.home');
});*/

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index')->name('admin.dashboard'); 
    
}); 

Route::middleware('auth')->group(function () {
    Route::middleware('verified')->group(function () {
        
        Route::name('admin.')->prefix('admin')->group(function () {
            Route::get('/', 'App\Http\Controllers\Admin\DashboardController@index');
            Route::get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index')->name('dashboard');

            Route::name('profil.')->prefix('profil')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\ProfilController@index')->name('index'); 
                Route::put('/', 'App\Http\Controllers\Admin\ProfilController@update')->name('update'); 
            });
            

            Route::name('artikel.')->prefix('artikel')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\ArtikelController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\ArtikelController@dt')->name('dt');
                Route::get('/create', 'App\Http\Controllers\Admin\ArtikelController@create')->name('create'); 
                Route::get('/edit/{id}', 'App\Http\Controllers\Admin\ArtikelController@edit')->name('edit'); 
                Route::post('/store', 'App\Http\Controllers\Admin\ArtikelController@store')->name('store');
                Route::put('/update/{id}', 'App\Http\Controllers\Admin\ArtikelController@update')->name('update');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\ArtikelController@destroy')->name('delete');  
            });

            Route::name('kategori.')->prefix('kategori')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\KategoriController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\KategoriController@dt')->name('dt'); 
                Route::get('/create', 'App\Http\Controllers\Admin\KategoriController@create')->name('create'); 
                Route::post('/store', 'App\Http\Controllers\Admin\KategoriController@store')->name('store');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\KategoriController@destroy')->name('delete'); 
            });

            Route::name('pengguna.')->prefix('pengguna')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\PenggunaController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\PenggunaController@dt')->name('dt'); 
                Route::get('/create', 'App\Http\Controllers\Admin\PenggunaController@create')->name('create'); 
                Route::get('/edit/{id}', 'App\Http\Controllers\Admin\PenggunaController@edit')->name('edit'); 
                Route::post('/store', 'App\Http\Controllers\Admin\PenggunaController@store')->name('store');
                Route::put('/update/{id}', 'App\Http\Controllers\Admin\PenggunaController@update')->name('update');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\PenggunaController@destroy')->name('delete'); 
            });

        });
    }); 
}); 

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/seeallartikel', [App\Http\Controllers\HomeController::class, 'seeAllArtikel'])->name('seeall');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('kategori/{slug}', [App\Http\Controllers\KategoriController::class, 'getSlug'])->name('kategori');
Route::get('artikel/{slug}', [App\Http\Controllers\ArtikelController::class, 'seeArtikel'])->name('artikel');


// Route::resource('user', [App\Http\Controllers\PenggunaController::class, 'index']);

// login google
Route::get('login/google', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('/login/google/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGoogleCallback']);

Route::get('/instagram', function () {
    return view('web.instagramporto');
});

app/Http/Controllers/Admin/ProfilController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth; 
use Illuminate\Validation\Rules\Password;
use Illuminate\Support\Facades\Hash; 
use Illuminate\Support\Facades\Session;

class ProfilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.profil.edit');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        /**/
        if(!is_null(Auth::user()->password)){
            $validated = $request->validate([
                'password_old' => ['required'],
                'password' => ['required', Password::min(6), 'confirmed'], 
            ]);
            if (Hash::check($request->password_old, Auth::user()->password) == FALSE) {
                Session::flash('message', ['text'=>'Password Lama Tidak Sesuai','type'=>'danger']);
            }else{
                $user = User::where("id",Auth::user()->id)->update([
                    "password" => Hash::make($request->password)
                ]);
                Session::flash('message', ['text'=>'Berhasil Set Password','type'=>'success']);
            }
        }else{
            $validated = $request->validate([
                'password' => ['required', Password::min(6), 'confirmed'], 
            ]);
            $user = User::where("id",Auth::user()->id)->update([
                "password" => Hash::make($request->password)
            ]);
            Session::flash('message', ['text'=>'Berhasil Set Password','type'=>'success']);
        }
        return redirect()->back();

        // return Auth::user()->name;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {
        //
    }
}

resources/views/admin/profil/edit.blade.php
	@extends('admin.layout')

	@section('title', 'Edit Profile | ' . config('app.name'))
	@section('content')
	<!-- Profile Image -->
    <div class="card card-primary card-outline">
      <div class="card-body box-profile">
        <div class="text-center">
          <img class="profile-user-img img-fluid img-circle"
               src="@if(!empty(Auth::user()->avatar)){{ Storage::disk('public')->url(Auth::user()->avatar) }}@else{{ asset('admin/img/avatar.png') }}@endif">
        </div>

        <h3 class="profile-username text-center">{{ Auth::user()->name }}</h3>

        @if(Auth::user()->google_id)
        	<p class="text-muted text-center">Akun Terkoneksi Ke Google</p>
        @endif        
        @if(Session::has('message'))
		    <div class="alert alert-{{session('message')['type']}}">
		        {{session('message')['text']}}
		    </div>
		@endif
		@if ($errors->any())
		    <div class="alert alert-danger">
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </div>
		@endif
        <form class="form-horizontal" action="{{ route('admin.profil.update') }}" method="POST">
        	@method('PUT')
            @csrf
            @if((!is_null(Auth::user()->password)) || (!empty(Auth::user()->password)) || (Auth::user()->password != ""))

            	<div class="form-group row">
					<label for="inputName" class="col-sm-2 col-form-label">Password Lama</label>
					<div class="col-sm-10">
						<input type="password" class="form-control" name="password_old" id="password_old" placeholder="Password Lama">
					</div>
				</div>
            	<div class="form-group row">
					<label for="inputName" class="col-sm-2 col-form-label">Password</label>
					<div class="col-sm-10">
						<input type="password" class="form-control" name="password" id="password" placeholder="Password">
					</div>
				</div>
				<div class="form-group row">
					<label for="inputName" class="col-sm-2 col-form-label">Konfirmasi Password</label>
					<div class="col-sm-10">
						<input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="Konfirmasi Password">
					</div>
				</div>	        	
	        @else
	        	<p class="text-muted text-center">Belum Set Password, Set Password Sekarang</p>

	        	<div class="form-group row">
					<label for="inputName" class="col-sm-2 col-form-label">Password</label>
					<div class="col-sm-10">
						<input type="password" class="form-control" name="password" id="password" placeholder="Password">
					</div>
				</div>
				<div class="form-group row">
					<label for="inputName" class="col-sm-2 col-form-label">Konfirmasi Password</label>
					<div class="col-sm-10">
						<input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="Konfirmasi Password">
					</div>
				</div>
	        @endif 
			<div class="form-group row">
				<div class="offset-sm-2 col-sm-10">
					<button type="submit" class="btn btn-danger">Submit</button>
				</div>
			</div>
		</form>

        {{-- <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a> --}}
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
	@endsection