routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('web.home');
});*/

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index')->name('admin.dashboard'); 
    
}); 

Route::middleware('auth')->group(function () {
    Route::middleware('verified')->group(function () {
        
        Route::name('admin.')->prefix('admin')->group(function () {
            Route::get('/', 'App\Http\Controllers\Admin\DashboardController@index');
            Route::get('/dashboard', 'App\Http\Controllers\Admin\DashboardController@index')->name('dashboard');

            Route::name('profil.')->prefix('profil')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\ProfilController@index')->name('index'); 
                Route::put('/', 'App\Http\Controllers\Admin\ProfilController@update')->name('update'); 
            });
            

            Route::name('artikel.')->prefix('artikel')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\ArtikelController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\ArtikelController@dt')->name('dt');
                Route::get('/create', 'App\Http\Controllers\Admin\ArtikelController@create')->name('create'); 
                Route::get('/edit/{id}', 'App\Http\Controllers\Admin\ArtikelController@edit')->name('edit'); 
                Route::post('/store', 'App\Http\Controllers\Admin\ArtikelController@store')->name('store');
                Route::put('/update/{id}', 'App\Http\Controllers\Admin\ArtikelController@update')->name('update');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\ArtikelController@destroy')->name('delete');  
            });

            Route::name('kategori.')->prefix('kategori')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\KategoriController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\KategoriController@dt')->name('dt'); 
                Route::get('/create', 'App\Http\Controllers\Admin\KategoriController@create')->name('create'); 
                Route::post('/store', 'App\Http\Controllers\Admin\KategoriController@store')->name('store');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\KategoriController@destroy')->name('delete'); 
            });

            Route::name('pengguna.')->prefix('pengguna')->group(function () {
                Route::get('/', 'App\Http\Controllers\Admin\PenggunaController@index')->name('index'); 
                Route::get('/datatable', 'App\Http\Controllers\Admin\PenggunaController@dt')->name('dt'); 
                Route::get('/create', 'App\Http\Controllers\Admin\PenggunaController@create')->name('create'); 
                Route::get('/edit/{id}', 'App\Http\Controllers\Admin\PenggunaController@edit')->name('edit'); 
                Route::post('/store', 'App\Http\Controllers\Admin\PenggunaController@store')->name('store');
                Route::put('/update/{id}', 'App\Http\Controllers\Admin\PenggunaController@update')->name('update');
                Route::delete('/delete/{id}', 'App\Http\Controllers\Admin\PenggunaController@destroy')->name('delete'); 
            });

        });
    }); 
}); 

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/seeallartikel', [App\Http\Controllers\HomeController::class, 'seeAllArtikel'])->name('seeall');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('kategori/{slug}', [App\Http\Controllers\KategoriController::class, 'getSlug'])->name('kategori');
Route::get('artikel/{slug}', [App\Http\Controllers\ArtikelController::class, 'seeArtikel'])->name('artikel');


// Route::resource('user', [App\Http\Controllers\PenggunaController::class, 'index']);

// login google
Route::get('login/google', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('/login/google/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGoogleCallback']);

Route::get('/instagram', function () {
    return view('web.instagramporto');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $guard_name = 'web';

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarUrlAttribute()
    {
        if ($this->avatar) {
            return Storage::disk('public')->url($this->avatar);
        }

        return config('app.default_avatar'); 
    }
}

resources/views/admin/user/index.blade.php
  @extends('admin.layout')

  @section('title', 'List Pengguna | ' . config('app.name'))

  @push('dt-style')
    <link rel="stylesheet" href="{{ asset('admin') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('admin') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('admin') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
  @endpush

  @section('content')
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          @if(Session::has('message'))
              <div class="alert alert-{{session('message')['type']}}">
                  {{session('message')['text']}}
              </div>
          @endif
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-md-6">
                  <h3>Kategori</h3>
                </div>
                <div class="col-md-6">
                  <a href="{{ route('admin.kategori.create') }}" class="btn btn-success float-right">Buat Baru</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">

          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="tabel-kategori" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nama</th>
                  <th>Slug</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <div class="modal fade" id="modal-sm">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Konfirmasi Hapus</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Konfirmasi Untuk Menghapus</p>
          </div>
          <div class="modal-footer justify-content-between">
            <form action="" method="POST" id="form-modal-hapus-konfirmasi">
              @csrf
              @method('delete')
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
   </section>
  @endsection

  @push('dt-skrip')
    <!-- DataTables  & Plugins -->
    <script src="{{ asset('admin') }}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/jszip/jszip.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="{{ asset('admin') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- SweetAlert2 -->
    <script src="{{ asset('admin') }}/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="{{ asset('admin') }}/plugins/toastr/toastr.min.js"></script>
    <script type="text/javascript">

    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
    });

    function hapus(a){
      var url = $("#"+a).data('link');
      $("#form-modal-hapus-konfirmasi").attr('action', url);
    }

    $(function () {

      var table = $('#tabel-kategori').DataTable({
        processing: true,
        serverSide: true,
        "paging": true,
        "lengthChange": true,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": true,
        "responsive": true,
        ajax: "{{ route('admin.kategori.dt') }}",
        columns: [
          // {data: 'id', name: 'id'},
          {data: 'name', name: 'name'},
          {data: 'slug', name: 'slug'},
          {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
      });



    });
    </script>
  @endpush